name: ddust
channels:
  - conda-forge
dependencies:
  - python
  - geopandas
  - geemap
  - numpy
  - pandas
  - requests
  - ipywidgets
  - rasterio
  - rasterstats
  - rioxarray
  - pip
  - pip:
    - ee
    - matplotlib
    - plotly
    - shapely
    - scipy
    - sodapy
    - cdsapi
    
