name: ddust
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - numpy
  - pandas
  - cdsapi
  - requests
  - ipywidgets
  - zipfile
  - rasterio
  - rasterstats
  - rioxarray
  - shapely
  - pip:
    - geemap 
    - ee
    - matplotlib
    - plotly
    - scipy
    - sodapy
    - os
    - json
    - datetime
    
