name: ddust

channels:
  - conda-forge
  - defaults

dependencies:
  # Main Python
  - python=3.8

  # Earth Engine
  - earthengine-api
  - geemap
  
  #Other
  - geopandas 
  - pandas
  - requests 
  - cdsapi
  - xarray
