name: ddust
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - geemap
  - numpy
  - pandas
  - requests
  - ipywidgets
  - rasterio
  - rasterstats
  - rioxarray
  - shapely
  - pip:
    - ee
    - matplotlib
    - plotly
    - scipy
    - sodapy
    - json
    - datetime
    - zipfile
    - cdsapi
    
