name: example-environment
  - conda-forge
dependencies:
  - python
  - geopandas
  - numpy
  - pandas
  - ipywidgets
  - mgwr
  - mlxtend
  - scikit-learn
  - pip
  - scipy
  - warning
  - pip:
    - plotly
    - scipy